name = "backend-for-portfolio"
compatibility_date = "2024-08-05"

workers_dev = true

[[r2_buckets]]
binding = "PROJECT_IMAGES"
bucket_name = "project-images"

# [vars]
# MY_VAR = "my-variable"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "id"

#[[r2_buckets]]
#binding = "PROJECT_IMAGES"
#bucket_name = "project-images"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"